name: Build executable

on:
  push:
    branches:
      - main

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '22.5.1'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        npm i -g yarn
        yarn
        
    - name: Build backend
      run: yarn build:python

    - name: Build App
      run: yarn make

    - name: Upload Ubuntu artifact
      uses: actions/upload-artifact@v3
      with:
        name: ubuntu-artifact
        path: out/make/deb/x64/*.deb


  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '22.5.1'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        npm i -g yarn
        yarn

    - name: Build backend
      run: yarn build:python

    - name: Build App
      run: yarn make

    - name: Upload macOS artifact
      uses: actions/upload-artifact@v3
      with:
        name: macos-artifact
        path: out/make/*.dmg

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '22.5.1'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        npm i -g yarn
        yarn

    - name: Build backend
      run: yarn build:python

    - name: Build App
      run: yarn make

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-artifact
        path: out/make/zip/win32/x64/*.zip

  create-release:
    needs: [ build-ubuntu, build-macos, build-windows ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_latest_tag
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_OUTPUT

      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          token: ${{ secrets.LISA }}
          tag: ${{ steps.get_latest_tag.outputs.LATEST_TAG }}
          release_name: Release ${{ steps.get_latest_tag.outputs.LATEST_TAG }}
          draft: true
          prerelease: false
          artifacts: "ubuntu-artifact/*,macos-artifact/*,windows-artifact/*"
