name: Build executable

on:
  push:
    tags:
      - '*'

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        npm i -g yarn
        yarn
        
    - name: Build backend
      run: yarn build:backend

    - name: Build App
      run: yarn make

    - name: Upload Ubuntu artifact
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu-artifact
        path: out/make/deb/x64/*.deb


  build-macos:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        npm i -g yarn
        yarn

    - name: Build backend
      run: yarn build:backend

    - name: Build App
      run: yarn make

    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-artifact
        path: out/make/zip/darwin/arm64/*.zip

  build-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        npm i -g yarn
        yarn

    - name: Build backend
      run: yarn build:backend

    - name: Build App
      run: yarn make

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-artifact
        path: out/make/zip/win32/x64/*.zip

  create-release:
    needs: [ build-ubuntu, build-macos, build-windows ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          token: ${{ secrets.LISA }}
          tag: ${{ steps.get_version.outputs.VERSION }}
          name: LiSA ${{ steps.get_version.outputs.VERSION }}
          draft: true
          prerelease: false
          artifacts: "ubuntu-artifact/*,macos-artifact/*,windows-artifact/*"
